// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.543
package layout

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import "context"
import "io"
import "bytes"

func Base() templ.Component {
	return templ.ComponentFunc(func(ctx context.Context, templ_7745c5c3_W io.Writer) (templ_7745c5c3_Err error) {
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templ_7745c5c3_W.(*bytes.Buffer)
		if !templ_7745c5c3_IsBuffer {
			templ_7745c5c3_Buffer = templ.GetBuffer()
			defer templ.ReleaseBuffer(templ_7745c5c3_Buffer)
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<html class=\"h-full\"><head><script src=\"https://cdn.tailwindcss.com\"></script><link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/8.0.1/normalize.min.css\"></head><body class=\"h-full bg-gradient-to-br from-purple-600 via-indigo-600 to-blue-600\"><header class=\"flex justify-between items-center py-4 px-8\"><a href=\"/\" class=\"flex items-center\"><img src=\"logo.svg\" alt=\"Logo\" class=\"h-8 w-auto\"><h1 class=\"text-white text-xl ml-2 font-bold\">Your App Name</h1></a><div><nav class=\"flex items-center\"><a href=\"/projects\" class=\"text-white hover:text-gray-200 mr-4\">Projects</a> <a href=\"/about\" class=\"text-white hover:text-gray-200 mr-4\">About</a> <a href=\"/auth\" class=\"text-white hover:text-gray-200 mr-4\">Sign In</a> <a href=\"/auth\" class=\"text-white hover:text-gray-200\">Sign Up</a></nav></div></header><main class=\"flex flex-col items-center justify-center h-full\"><h1 class=\"text-3xl font-bold text-white mb-8\">Welcome to Your App</h1>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("</main><footer class=\"text-center text-white py-4\"><p>&copy; 2024 Your App. All rights reserved.</p></footer></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if !templ_7745c5c3_IsBuffer {
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteTo(templ_7745c5c3_W)
		}
		return templ_7745c5c3_Err
	})
}
